#!/usr/bin/env bash
# Join the ONOS "Flows" view to the TwinLight service list.
#
#   correlate.sh          one row per ONOS flow, with the twin's service and physics
#   correlate.sh --json   the same join as JSON
#
# The two systems share no identifier. ONOS's flow id is generated inside ONOS
# and never leaves it; the T-API connectivity-service UUID is generated by the
# ODTN driver per flow rule and never appears in the Flows view. What they do
# share is the **in/out port pair** — ONOS keys its flow on it, and the adapter
# records it against the service it created. That pair is the join key, and the
# adapter also stamps it into the service's T-API name so the correlation is
# visible in the TwinLight UI without running this script at all.

. "$(dirname "$0")/lib.sh"

require_stack

JSON="$(python3 - "$@" <<PY
import json, sys, urllib.request, base64

sys.path.insert(0, "${SCRIPT_DIR}")
from tapi_fields import spectrum_of

onos_auth = base64.b64encode(b"${ONOS_AUTH}").decode()

def get(url, auth=False):
    req = urllib.request.Request(url)
    if auth:
        req.add_header("Authorization", "Basic " + onos_auth)
    return json.load(urllib.request.urlopen(req))

flows = get("${ONOS_URL}/onos/v1/flows/${DEVICE_ID}", auth=True).get("flows", [])
status = get("${ADAPTER_URL}/adapter/status")
endpoints = status.get("service-endpoints", {})
services = status.get("onos-created-services", {})

# port pair -> service uuid
by_pair = {}
for uuid, ep in endpoints.items():
    if ep.get("onos-port-pair"):
        by_pair[ep["onos-port-pair"]] = uuid

rows = []
for f in flows:
    if f.get("appId") != "org.onosproject.rest":
        continue
    ins = [c["port"] for c in f["selector"]["criteria"] if c["type"] == "IN_PORT"]
    outs = [i["port"] for i in f["treatment"]["instructions"] if i["type"] == "OUTPUT"]
    if not ins or not outs:
        continue
    pair = "%s->%s" % (ins[0], outs[0])
    uuid = by_pair.get(pair)

    row = {
        "onos-flow-id": f["id"],
        "onos-state": f["state"],
        "onos-port-pair": pair,
        "twin-service-uuid": uuid,
        "a-end": None, "z-end": None, "km": None,
        "gsnr-db": None, "osnr-db": None, "ber": None,
        "centre-thz": None, "twin-status": None,
    }

    if uuid:
        ep = endpoints.get(uuid, {})
        row["a-end"], row["z-end"] = ep.get("a-end"), ep.get("z-end")
        svc = services.get(uuid, {}).get("tapi-connectivity:connectivity-service", {})
        band = spectrum_of(svc)
        row["centre-thz"] = round(band[0], 4) if band else None
        try:
            opm = get("${TWIN_URL}/internal/opm/" + uuid)
            info = get("${TWIN_URL}/internal/services/" + uuid)
            m = opm["measurements"]
            row["twin-status"] = opm.get("status", "ok")
            row["gsnr-db"], row["osnr-db"] = m.get("gsnr-db"), m.get("osnr-db")
            row["ber"], row["km"] = m.get("pre-fec-ber"), info.get("total-fiber-km")
        except Exception:
            row["twin-status"] = "unreachable"

    rows.append(row)

rows.sort(key=lambda r: (r["twin-service-uuid"] is None, -(r["gsnr-db"] or -99)))
print(json.dumps(rows))
PY
)" || die "could not build the join"

if [ "${1:-}" = "--json" ]; then
  printf '%s\n' "${JSON}" | python3 -m json.tool
  exit 0
fi

printf '%s' "${JSON}" | python3 -c "
import json, sys
rows = json.load(sys.stdin)
if not rows:
    print('  no ONOS-provisioned flows on this device')
    raise SystemExit

num = lambda v, f: (f % v) if isinstance(v, (int, float)) else '--'
print()
print('  %-20s %-12s %-7s %-26s %-10s %8s %8s %10s'
      % ('ONOS FLOW ID', 'ONOS STATE', 'PORTS', 'LIGHTPATH', 'SERVICE', 'KM', 'GSNR dB', 'BER'))
print('  ' + '-' * 112)
for r in rows:
    ends = ('%s -> %s' % (r['a-end'], r['z-end'])) if r['a-end'] else '(not correlated)'
    svc = (r['twin-service-uuid'] or '')[:8] or '--'
    print('  %-20s %-12s %-7s %-26s %-10s %8s %8s %10s'
          % (r['onos-flow-id'], r['onos-state'], r['onos-port-pair'], ends[:26], svc,
             num(r['km'], '%.1f'), num(r['gsnr-db'], '%.2f'), num(r['ber'], '%.1e')))

orphan_flows = [r for r in rows if not r['twin-service-uuid']]
print()
if orphan_flows:
    print('  %d flow(s) with no twin service: the twin refused them, or they' % len(orphan_flows))
    print('  predate the adapter. Check %s/adapter/status.' % '${ADAPTER_URL}')
else:
    print('  every ONOS flow maps to a live lightpath on the twin')
print()
"
